### ISSUE TITLE
Being able to disable/reorder song in the playlist

### ISSUE THREAD

**Issue by saefr** [nikarh/reaper-remote-bandui#4]
Hi nikarh ! Thanks for your incredible work, it helps us a lot (we are a little rock french band), it's the perfect solution for us since we already use a tablet to work with our mixing desk. 

I think one of the missing part of the project is a way to reorder or disable songs. With 15+ songs, changing the playlist is not so difficult but take a lot of time. And if you want to remove one, you cant "disable" it and keep it in the project, it will show on the web interface

I dont see yet the best way to do it, maybe using the SWS Region Playlist plugin behind your work ? You seems to have a better understanding of the Reaper code than me :D 

Anyway, have a good day and thanks a lot !

**Comment by nikarh** [comment]
Hi there, I'm happy to hear this project is useful for you and your band!

That's an interesting idea, but I don't know which approach is the most suitable for that.
Also, this can be divided into multiple problems.

- Do you need a playlist, like a setlist for a live show with predetermined pauses between songs, so that you hit "play" and it plays the whole setlist in a predetermined way?
- Do you need to have multiple different playlists like that and the ability to switch between them?
- Should these playlists be manageable only in the web UI, or should it be possible to also do that in REAPER itself?

Obviously, the info about ordering, enabled/disabled flags, and playlists should be stored somewhere in the project.
I've never used SWS Region Playlist, and not sure how it keeps the data, but without depending on it I see a couple of ways how this info can be encoded:

- Regions have a numeric ID, which can be used for ordering
- Some convention can be introduced for sorting and enabling, like a text prefix/suffix in the region name
- The ordering functionality may move regions on the grid (though I would rather not be doing that, there can be some foot guns, since all markers and tempo changes and items must also be moved, and there are edge cases, like audio items that continue after the region or start before the region, not sure how they can be moved)
- Use empty text items on the grid and encode info inside

If this is implemented in a DIY approach it can translate nicely into a web UI, but may be somewhat annoying to work with in Reaper itself.
If the solution relies on SWS Region Playlist, then SWS becomes a hard dependency for this UI, which is not ideal (even though probably everybody using Reaper has SWS).

Would be glad if you could address these questions and challenge the proposed approaches, as a potential user of this feature you probably have a good understanding of how you would use that.

Regarding #5, I would rather do these changes one at a time, but the same applies to that - it would be nice if you could elaborate on how you see that in the UI, like do you want a grid, or just next/prev buttons. May be do a quick sketch of the potential UI for that?

**Comment by saefr** [comment]
I think the best approach is the simplest. Your UI is the one i choose to work with because its the only one easy to use and manage, with no hard dependencies. And it looks nice :) Better keep it that way ! 

The playlist solution doesnt seems the best option for this kind of use, there is already good projects thats does it : Song Switcher, SWS Region Playlist, etc ... Your project doesnt do a playlist, it only provide a good .rpp file with a solid fundation, and read all the regions. It's simple, no need to complicate thing here. But it can be a background one day if you want to do something bigger, i suppose.

You are right about the ordering and the suffix/prefix in the region name. In my opinion, its the best and easier way to store the information and order what you need.

I propose this approach : using a prefix directly to order the region or disable them. If your region is named "1#Song1" (for the example :D), it's first in the interface. If its named "OFF#Song2" it doesnt display in the UI.  

And maybe, if the prefix doesnt exist in the name, it shows in the numeric order of Reaper. 

It means you cant "Go to the next region" after ending the actual one, but use a "Go to the region xx" instead, because they are not displayed in the Web ui the same as in the Reaper File. But it means you never have to reorder or change anything in the Reaper itself (and avoid the edge cases of moving the regions), only the display is different. And pretty much no visual changes or actions in the web ui interface.

What do you think about it ? 

And thanks to your quick response by the way ! 💯

**Comment by nikarh** [comment]
Sounds reasonable. I like the idea of the simplest approach since we can always iterate on that later. Using region names would be very straightforward.

>And pretty much no visual changes or actions in the web ui interface.

I think it would be pretty cool though to add a toggle that switches the region list into an "edit mode", where you can rearrange the order and enable/disable the regions, that should be pretty straightforward to implement.

**Comment by saefr** [comment]
> I think it would be pretty cool though to add a toggle that switches the region list into an "edit mode", where you can rearrange the order and enable/disable the regions, that should be pretty straightforward to implement.

I'm not the one doing the work, so why not ! The problem is storing the data, if you do something like that it will goes away after a web refresh. Or maybe if it changes dynamically the name of the region, then its gonna work 👍

**Comment by nikarh** [comment]
> I'm not the one doing the work, so why not ! The problem is storing the data, if you do something like that it will goes away after a web refresh. Or maybe if it changes dynamically the name of the region, then its gonna work 👍

Yes, I'm planning for the controls to actually rename the regions in the Reaper project

**Comment by saefr** [comment]
Seems perfect to me ! and i think it solve pretty much anything needed about the reordering or enable/disable concept.
For the other idea about the markers navigation, i'm gonna answer directly on the issue :) 
Thanks you again !

**Comment by nikarh** [comment]
Seems that there is no easy way to rename regions via API.

Good thing though is that Reaper provides commands for reading/writing arbitrary text data that is saved with the project. In the end I used this approach - the order and enabled status are encoded and concatenated as a string and stored in this `PROJEXTSTATE`.

Take a look at https://github.com/nikarh/reaper-remote-bandui/actions/runs/8306615036, there is a build artifact there with these changes.
Let me know if that works for you, and if it does I'll merge that to main.

**Comment by saefr** [comment]
I tried it, it works perfeclty as intended :) Thank you very much, it's a real improvment to our usage and i hope for the project itself 🥇

Using it this morning, i also have few little ideas or reflexions to share : 
- When the song is playing, you had a nice little counter for the time on the right. Isnt it better to have it begin at zero and increase at the cursor goes in the region ? And have the lenght of the region itself on the righ of the countdown ? Like "0:34 / 3:50" for a 03min:50s region
- You added a light white color on the background of the playing region, maybe a little green border around it when its playing will help us for the visual aspect ? Just the background white when its "on the region" itself and selected, and something green when its playing the region.
- And one little bug i found : when you end a region and goes to the next, you still have a light border around the previous one, like it's still selected. If its possible to remove it, it will increase the visual aspect of the UI :) 

have a nice week-end by the way 👍

**Comment by nikarh** [comment]
Hey, happy it works for you :)

All comments make sense.

> When the song is playing, you had a nice little counter for the time on the right. Isnt it better to have it begin at zero and increase at the cursor goes in the region ? And have the lenght of the region itself on the righ of the countdown ? Like "0:34 / 3:50" for a 03min:50s region

That was the initial idea, not sure why I decided to show it the reaper way in the end. That's a real easy one.

> You added a light white color on the background of the playing region, maybe a little green border around it when its playing will help us for the visual aspect ? Just the background white when its "on the region" itself and selected, and something green when its playing the region.

Actually in this PR I changed the visual style of the region button because I wanted to support region colors as per screenshots below. But having a clear indicator of the active song especially now that colors can be different would make it better. I think I'll do the border/outline of something like green/yellow/red for different states (playing/paused/stopped or even recording)

![image](https://github.com/nikarh/reaper-remote-bandui/assets/5517011/d2e1613a-8b20-48be-9f0a-1f25d423bb31)
![image](https://github.com/nikarh/reaper-remote-bandui/assets/5517011/48756091-0666-44fe-84ed-8bcb18b31ea5)


> And one little bug i found : when you end a region and goes to the next, you still have a light border around the previous one, like it's still selected. If its possible to remove it, it will increase the visual aspect of the UI :)

Yeah, even though it's technically a html button with all the usual focus rules applied, this particular project doesn't really care about control from keyboard and accessibility, as it is meant to be used on a phone/table. I'll just remove the `:focus` css from these buttons as they are unnecessary. An easy one

**Comment by saefr** [comment]
#


> Actually in this PR I changed the visual style of the region button because I wanted to support region colors as per screenshots below. But having a clear indicator of the active song especially now that colors can be different would make it better. I think I'll do the border/outline of something like green/yellow/red for different states (playing/paused/stopped or even recording)

Adding a little bit of color can really help to work with the project, since all the interface itself is pretty minimalist and black/white, the little color you add will pop immediately and really help the vizualisation. 

> That was the initial idea, not sure why I decided to show it the reaper way in the end. That's a real easy one.

> Yeah, even though it's technically a html button with all the usual focus rules applied, this particular project doesn't really care about control from keyboard and accessibility, as it is meant to be used on a phone/table. I'll just remove the `:focus` css from these buttons as they are unnecessary. An easy one

Nice 🥇

**Comment by nikarh** [comment]
~I've updated the PR with these changes, the artifact is in this build - https://github.com/nikarh/reaper-remote-bandui/actions/runs/8307241520~

Let me know if alls good :)

**Comment by nikarh** [comment]
Oh, wait, it seems these outlines don't work on a real phone, I'll change them to borders

This one should do
https://github.com/nikarh/reaper-remote-bandui/actions/runs/8307406003

**Comment by saefr** [comment]
Tried on Ubuntu Firefox and an Android tablet, its perfect. Work really well and does the job 💯 

You wanted to also change the color of the region itself in Reaper as you did in your screenshot ? Didnt saw it in this PR

**Comment by nikarh** [comment]
> You wanted to also change the color of the region itself in Reaper as you did in your screenshot ? Didnt saw it in this PR

Nope, I didn't set colors in the example project in the repo and update the screenshots, will update it and merge that.
Happy to hear this works for you and your band!
